name: Update README daily

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: npm install
      - run: node index.js
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ClementYziquel5
          author_email:
          message: "Update README daily"
          add: "README.md"
          signoff: true 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: main
```

