name: Update README daily

on:
  schedule:
    #every day at 00:00 UTC+2
    - cron: "0 0 * * *"
  #manual trigger
  workflow_dispatch:



jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - run: node index.js
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: python root-me.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ClementYziquel5
          message: "Update README daily"
          add: "README.md"
          signoff: true 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: main

